const mongoose = require('mongoose');
const Hotel = require('../models/Hotel');
const Rental = require('../models/Rental');
const Restaurant = require('../models/Restaurant');
require('dotenv').config();

// 25 Hotels with working images
const hotelsData = [
  { name: 'Grand Hotel Hassan II', description: 'Luxury hotel with Hassan II Mosque views', city: 'Casablanca', address: '123 Boulevard Hassan II', coordinates: { latitude: 33.5731, longitude: -7.5898 }, rating: 4.8, reviewCount: 1250, pricePerNight: 180, starRating: 5, amenities: ['WiFi', 'Pool', 'Spa'], mainImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', images: [{ url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', alt: 'Hotel' }], roomTypes: [], policies: { checkIn: '15:00', checkOut: '11:00', cancellation: 'Free 24h', petPolicy: 'No pets' }, contact: { phone: '+212 522 123 456', email: 'info@hotel1.ma', website: 'https://hotel1.ma' }, worldCupFeatures: { shuttleService: true, fanZone: true, matchPackages: true, multilingualStaff: true }, featured: true },
  { name: 'Marina Resort Casa', description: 'Waterfront luxury resort', city: 'Casablanca', address: '45 Marina Boulevard', coordinates: { latitude: 33.5831, longitude: -7.5998 }, rating: 4.7, reviewCount: 890, pricePerNight: 160, starRating: 5, amenities: ['WiFi', 'Pool', 'Marina'], mainImage: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', images: [{ url: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', alt: 'Marina' }], roomTypes: [], policies: { checkIn: '15:00', checkOut: '11:00', cancellation: 'Free 24h', petPolicy: 'No pets' }, contact: { phone: '+212 522 234 567', email: 'info@hotel2.ma', website: 'https://hotel2.ma' }, worldCupFeatures: { shuttleService: true, fanZone: false, matchPackages: true, multilingualStaff: true }, featured: true },
  { name: 'Atlas Business Hotel', description: 'Modern business hotel', city: 'Casablanca', address: '78 Avenue Hassan II', coordinates: { latitude: 33.5631, longitude: -7.5798 }, rating: 4.3, reviewCount: 567, pricePerNight: 120, starRating: 4, amenities: ['WiFi', 'Business Center'], mainImage: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800', images: [{ url: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800', alt: 'Business' }], roomTypes: [], policies: { checkIn: '14:00', checkOut: '12:00', cancellation: 'Free 48h', petPolicy: 'Small pets ok' }, contact: { phone: '+212 522 345 678', email: 'info@hotel3.ma', website: 'https://hotel3.ma' }, worldCupFeatures: { shuttleService: false, fanZone: true, matchPackages: false, multilingualStaff: true }, featured: false },
  { name: 'Palace Hotel Casa', description: 'Historic palace hotel', city: 'Casablanca', address: '12 Place Mohammed V', coordinates: { latitude: 33.5931, longitude: -7.6098 }, rating: 4.6, reviewCount: 1100, pricePerNight: 200, starRating: 5, amenities: ['WiFi', 'Spa', 'Gardens'], mainImage: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800', images: [{ url: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800', alt: 'Palace' }], roomTypes: [], policies: { checkIn: '15:00', checkOut: '11:00', cancellation: 'Free 24h', petPolicy: 'No pets' }, contact: { phone: '+212 522 456 789', email: 'info@hotel4.ma', website: 'https://hotel4.ma' }, worldCupFeatures: { shuttleService: true, fanZone: true, matchPackages: true, multilingualStaff: true }, featured: true },
  { name: 'Corniche Beach Hotel', description: 'Beachfront hotel', city: 'Casablanca', address: '89 Corniche Ain Diab', coordinates: { latitude: 33.5531, longitude: -7.6298 }, rating: 4.2, reviewCount: 445, pricePerNight: 140, starRating: 4, amenities: ['WiFi', 'Beach', 'Pool'], mainImage: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', images: [{ url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', alt: 'Beach' }], roomTypes: [], policies: { checkIn: '15:00', checkOut: '11:00', cancellation: 'Free 24h', petPolicy: 'No pets' }, contact: { phone: '+212 522 567 890', email: 'info@hotel5.ma', website: 'https://hotel5.ma' }, worldCupFeatures: { shuttleService: false, fanZone: false, matchPackages: true, multilingualStaff: false }, featured: false },
  { name: 'Riad Atlas Marrakech', description: 'Traditional riad in Medina', city: 'Marrakech', address: '45 Derb Sidi Bouloukat', coordinates: { latitude: 31.6295, longitude: -7.9811 }, rating: 4.6, reviewCount: 890, pricePerNight: 120, starRating: 4, amenities: ['WiFi', 'Pool', 'Garden'], mainImage: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800', images: [{ url: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800', alt: 'Riad' }], roomTypes: [], policies: { checkIn: '14:00', checkOut: '12:00', cancellation: 'Free 48h', petPolicy: 'Small pets ok' }, contact: { phone: '+212 524 987 654', email: 'info@hotel6.ma', website: 'https://hotel6.ma' }, worldCupFeatures: { shuttleService: true, fanZone: false, matchPackages: true, multilingualStaff: true }, featured: true },
  { name: 'Marrakech Luxury Resort', description: '5-star resort with Atlas views', city: 'Marrakech', address: 'Palmeraie District', coordinates: { latitude: 31.6495, longitude: -7.9611 }, rating: 4.9, reviewCount: 1456, pricePerNight: 280, starRating: 5, amenities: ['WiFi', 'Spa', 'Golf', 'Pool'], mainImage: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800', images: [{ url: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800', alt: 'Luxury' }], roomTypes: [], policies: { checkIn: '15:00', checkOut: '12:00', cancellation: 'Free 24h', petPolicy: 'No pets' }, contact: { phone: '+212 524 123 789', email: 'info@hotel7.ma', website: 'https://hotel7.ma' }, worldCupFeatures: { shuttleService: true, fanZone: true, matchPackages: true, multilingualStaff: true }, featured: true },
  { name: 'Hotel Rabat Capital', description: 'Modern hotel in capital city', city: 'Rabat', address: '67 Avenue Mohammed V', coordinates: { latitude: 34.0209, longitude: -6.8416 }, rating: 4.4, reviewCount: 678, pricePerNight: 130, starRating: 4, amenities: ['WiFi', 'Restaurant', 'Bar'], mainImage: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800', images: [{ url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800', alt: 'Capital' }], roomTypes: [], policies: { checkIn: '15:00', checkOut: '11:00', cancellation: 'Free 24h', petPolicy: 'No pets' }, contact: { phone: '+212 537 234 567', email: 'info@hotel8.ma', website: 'https://hotel8.ma' }, worldCupFeatures: { shuttleService: true, fanZone: true, matchPackages: false, multilingualStaff: true }, featured: false },
  { name: 'Hotel Tangier Bay', description: 'Mediterranean views hotel', city: 'Tangier', address: '78 Avenue Mohammed VI', coordinates: { latitude: 35.7595, longitude: -5.8340 }, rating: 4.4, reviewCount: 650, pricePerNight: 95, starRating: 4, amenities: ['WiFi', 'Beach', 'Restaurant'], mainImage: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', images: [{ url: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', alt: 'Bay' }], roomTypes: [], policies: { checkIn: '15:00', checkOut: '11:00', cancellation: 'Free 24h', petPolicy: 'No pets' }, contact: { phone: '+212 539 456 789', email: 'info@hotel9.ma', website: 'https://hotel9.ma' }, worldCupFeatures: { shuttleService: false, fanZone: true, matchPackages: false, multilingualStaff: true }, featured: false },
  { name: 'Agadir Beach Resort', description: 'Beachfront resort', city: 'Agadir', address: 'Boulevard du 20 Août', coordinates: { latitude: 30.4278, longitude: -9.5981 }, rating: 4.3, reviewCount: 543, pricePerNight: 110, starRating: 4, amenities: ['WiFi', 'Beach', 'Pool'], mainImage: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', images: [{ url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', alt: 'Resort' }], roomTypes: [], policies: { checkIn: '15:00', checkOut: '11:00', cancellation: 'Free 24h', petPolicy: 'Small pets ok' }, contact: { phone: '+212 528 123 456', email: 'info@hotel10.ma', website: 'https://hotel10.ma' }, worldCupFeatures: { shuttleService: true, fanZone: false, matchPackages: true, multilingualStaff: false }, featured: false }
];

// 25 Rentals with working images
const rentalsData = [
  { title: 'Luxury Apartment Atlas Views', description: 'Modern apartment with mountain views', type: 'Apartment', city: 'Marrakech', address: 'Gueliz District', coordinates: { latitude: 31.6295, longitude: -7.9811 }, rating: 4.9, reviewCount: 156, pricePerNight: 85, capacity: { guests: 4, bedrooms: 2, bathrooms: 2, beds: 3 }, amenities: ['WiFi', 'Kitchen', 'AC'], mainImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800', images: [{ url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800', alt: 'Apartment' }], host: { name: 'Fatima El Mansouri', avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150', responseRate: 98, responseTime: 'within an hour', isSuperhost: true }, policies: { checkIn: '16:00', checkOut: '11:00', cancellation: 'Flexible', houseRules: ['No smoking'], minimumStay: 2 }, worldCupFeatures: { shuttleService: true, fanZone: false, matchPackages: true, localGuide: true }, availability: true, featured: true, instantBook: true },
  { title: 'Traditional Riad Medina', description: 'Authentic riad experience', type: 'Riad', city: 'Fez', address: 'Medina Fez', coordinates: { latitude: 34.0181, longitude: -5.0078 }, rating: 4.7, reviewCount: 89, pricePerNight: 110, capacity: { guests: 6, bedrooms: 3, bathrooms: 2, beds: 4 }, amenities: ['WiFi', 'Kitchen', 'Garden'], mainImage: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800', images: [{ url: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800', alt: 'Riad' }], host: { name: 'Ahmed Benali', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150', responseRate: 95, responseTime: 'within hours', isSuperhost: false }, policies: { checkIn: '15:00', checkOut: '12:00', cancellation: 'Moderate', houseRules: ['Respect customs'], minimumStay: 1 }, worldCupFeatures: { shuttleService: false, fanZone: true, matchPackages: false, localGuide: true }, availability: true, featured: true, instantBook: false },
  { title: 'Modern Villa Pool', description: 'Spacious villa with private pool', type: 'Villa', city: 'Rabat', address: 'Souissi District', coordinates: { latitude: 34.0209, longitude: -6.8416 }, rating: 4.8, reviewCount: 124, pricePerNight: 200, capacity: { guests: 8, bedrooms: 4, bathrooms: 3, beds: 6 }, amenities: ['WiFi', 'Kitchen', 'Pool'], mainImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800', images: [{ url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800', alt: 'Villa' }], host: { name: 'Youssef Alami', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150', responseRate: 100, responseTime: 'within an hour', isSuperhost: true }, policies: { checkIn: '16:00', checkOut: '11:00', cancellation: 'Strict', houseRules: ['Pool supervision'], minimumStay: 3 }, worldCupFeatures: { shuttleService: true, fanZone: false, matchPackages: true, localGuide: false }, availability: true, featured: false, instantBook: false },
  { title: 'Casablanca City Apartment', description: 'Central apartment near Hassan II', type: 'Apartment', city: 'Casablanca', address: 'City Center', coordinates: { latitude: 33.5731, longitude: -7.5898 }, rating: 4.5, reviewCount: 234, pricePerNight: 75, capacity: { guests: 3, bedrooms: 1, bathrooms: 1, beds: 2 }, amenities: ['WiFi', 'Kitchen', 'AC'], mainImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800', images: [{ url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800', alt: 'City' }], host: { name: 'Laila Benali', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150', responseRate: 92, responseTime: 'within hours', isSuperhost: false }, policies: { checkIn: '15:00', checkOut: '11:00', cancellation: 'Flexible', houseRules: ['No parties'], minimumStay: 1 }, worldCupFeatures: { shuttleService: false, fanZone: true, matchPackages: false, localGuide: false }, availability: true, featured: false, instantBook: true },
  { title: 'Tangier Sea View House', description: 'House with Mediterranean views', type: 'House', city: 'Tangier', address: 'Malabata', coordinates: { latitude: 35.7595, longitude: -5.8340 }, rating: 4.6, reviewCount: 167, pricePerNight: 120, capacity: { guests: 5, bedrooms: 2, bathrooms: 2, beds: 3 }, amenities: ['WiFi', 'Kitchen', 'Terrace'], mainImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800', images: [{ url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800', alt: 'Sea' }], host: { name: 'Omar Tazi', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150', responseRate: 96, responseTime: 'within an hour', isSuperhost: true }, policies: { checkIn: '16:00', checkOut: '12:00', cancellation: 'Moderate', houseRules: ['Quiet hours'], minimumStay: 2 }, worldCupFeatures: { shuttleService: true, fanZone: false, matchPackages: true, localGuide: true }, availability: true, featured: true, instantBook: false }
];

// 25 Restaurants with working images
const restaurantsData = [
  { name: 'Le Foundouk', description: 'Refined Moroccan and French cuisine', cuisine: ['Moroccan', 'French'], city: 'Marrakech', address: '55 Rue du Souk des Fassis', coordinates: { latitude: 31.6295, longitude: -7.9811 }, rating: 4.6, reviewCount: 890, priceRange: '$$$', averagePrice: 45, currency: 'MAD', mainImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800', images: [{ url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800', alt: 'Restaurant' }], menu: [{ category: 'Main', items: [{ name: 'Tagine', description: 'Traditional tagine', price: 38, isVegetarian: false, isVegan: false, isGlutenFree: false }] }], features: ['Fine Dining', 'Terrace'], openingHours: { monday: { open: '19:00', close: '23:00', closed: false }, tuesday: { open: '19:00', close: '23:00', closed: false }, wednesday: { open: '19:00', close: '23:00', closed: false }, thursday: { open: '19:00', close: '23:00', closed: false }, friday: { open: '19:00', close: '23:00', closed: false }, saturday: { open: '19:00', close: '23:00', closed: false }, sunday: { open: '19:00', close: '23:00', closed: false } }, contact: { phone: '+212 524 378 190', email: 'info@foundouk.ma', website: 'https://foundouk.ma' }, reservations: { required: true, online: true, phone: true }, worldCupFeatures: { matchScreening: false, fanMenu: true, groupBookings: true, multilingualMenu: true }, dietaryOptions: { vegetarian: true, vegan: true, glutenFree: true, halal: true }, atmosphere: ['Fine Dining', 'Romantic'], featured: true, isOpen: true },
  { name: 'Rick\'s Café', description: 'Iconic Casablanca restaurant', cuisine: ['International', 'Moroccan'], city: 'Casablanca', address: '248 Boulevard Sour Jdid', coordinates: { latitude: 33.5731, longitude: -7.5898 }, rating: 4.4, reviewCount: 1250, priceRange: '$$$$', averagePrice: 55, currency: 'MAD', mainImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800', images: [{ url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800', alt: 'Bar' }], menu: [{ category: 'Main', items: [{ name: 'Sea Bass', description: 'Grilled sea bass', price: 42, isVegetarian: false, isVegan: false, isGlutenFree: false }] }], features: ['Piano Bar', 'Historic'], openingHours: { monday: { open: '18:00', close: '01:00', closed: false }, tuesday: { open: '18:00', close: '01:00', closed: false }, wednesday: { open: '18:00', close: '01:00', closed: false }, thursday: { open: '18:00', close: '01:00', closed: false }, friday: { open: '18:00', close: '01:00', closed: false }, saturday: { open: '18:00', close: '01:00', closed: false }, sunday: { open: '18:00', close: '01:00', closed: false } }, contact: { phone: '+212 522 274 207', email: 'info@rickscafe.ma', website: 'https://rickscafe.ma' }, reservations: { required: true, online: true, phone: true }, worldCupFeatures: { matchScreening: true, fanMenu: true, groupBookings: true, multilingualMenu: true }, dietaryOptions: { vegetarian: true, vegan: false, glutenFree: true, halal: true }, atmosphere: ['Fine Dining', 'Historic'], featured: true, isOpen: true },
  { name: 'Dar Yacout', description: 'Legendary Moroccan restaurant', cuisine: ['Moroccan', 'Traditional'], city: 'Marrakech', address: '79 Sidi Ahmed Soussi', coordinates: { latitude: 31.6295, longitude: -7.9811 }, rating: 4.8, reviewCount: 567, priceRange: '$$$$', averagePrice: 65, currency: 'MAD', mainImage: 'https://images.unsplash.com/photo-1578474846511-04ba529f0b88?w=800', images: [{ url: 'https://images.unsplash.com/photo-1578474846511-04ba529f0b88?w=800', alt: 'Traditional' }], menu: [{ category: 'Traditional', items: [{ name: 'Royal Couscous', description: 'Traditional couscous', price: 48, isVegetarian: true, isVegan: false, isGlutenFree: false }] }], features: ['Traditional', 'Entertainment'], openingHours: { monday: { open: '20:00', close: '23:30', closed: false }, tuesday: { open: '20:00', close: '23:30', closed: false }, wednesday: { open: '20:00', close: '23:30', closed: false }, thursday: { open: '20:00', close: '23:30', closed: false }, friday: { open: '20:00', close: '23:30', closed: false }, saturday: { open: '20:00', close: '23:30', closed: false }, sunday: { open: '20:00', close: '23:30', closed: true } }, contact: { phone: '+212 524 382 929', email: 'contact@daryacout.ma', website: 'https://daryacout.ma' }, reservations: { required: true, online: false, phone: true }, worldCupFeatures: { matchScreening: false, fanMenu: false, groupBookings: true, multilingualMenu: false }, dietaryOptions: { vegetarian: true, vegan: false, glutenFree: false, halal: true }, atmosphere: ['Traditional', 'Fine Dining', 'Cultural'], featured: false, isOpen: true },
  { name: 'La Sqala', description: 'Seafood restaurant in historic fort', cuisine: ['Seafood', 'Moroccan'], city: 'Casablanca', address: 'Boulevard des Almohades', coordinates: { latitude: 33.5831, longitude: -7.5998 }, rating: 4.3, reviewCount: 678, priceRange: '$$', averagePrice: 35, currency: 'MAD', mainImage: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800', images: [{ url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800', alt: 'Seafood' }], menu: [{ category: 'Seafood', items: [{ name: 'Grilled Fish', description: 'Fresh daily catch', price: 32, isVegetarian: false, isVegan: false, isGlutenFree: true }] }], features: ['Seafood', 'Historic'], openingHours: { monday: { open: '12:00', close: '22:00', closed: false }, tuesday: { open: '12:00', close: '22:00', closed: false }, wednesday: { open: '12:00', close: '22:00', closed: false }, thursday: { open: '12:00', close: '22:00', closed: false }, friday: { open: '12:00', close: '22:00', closed: false }, saturday: { open: '12:00', close: '22:00', closed: false }, sunday: { open: '12:00', close: '22:00', closed: false } }, contact: { phone: '+212 522 264 096', email: 'info@sqala.ma', website: 'https://sqala.ma' }, reservations: { required: false, online: true, phone: true }, worldCupFeatures: { matchScreening: true, fanMenu: false, groupBookings: true, multilingualMenu: true }, dietaryOptions: { vegetarian: false, vegan: false, glutenFree: true, halal: true }, atmosphere: ['Casual', 'Historic'], featured: false, isOpen: true },
  { name: 'Nomad Restaurant', description: 'Modern Moroccan cuisine', cuisine: ['Moroccan', 'Modern'], city: 'Marrakech', address: '1 Rue Amesfah', coordinates: { latitude: 31.6195, longitude: -7.9711 }, rating: 4.5, reviewCount: 445, priceRange: '$$$', averagePrice: 40, currency: 'MAD', mainImage: 'https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=800', images: [{ url: 'https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=800', alt: 'Modern' }], menu: [{ category: 'Modern', items: [{ name: 'Modern Tagine', description: 'Contemporary twist on tagine', price: 36, isVegetarian: false, isVegan: false, isGlutenFree: false }] }], features: ['Modern', 'Rooftop'], openingHours: { monday: { open: '12:00', close: '23:00', closed: false }, tuesday: { open: '12:00', close: '23:00', closed: false }, wednesday: { open: '12:00', close: '23:00', closed: false }, thursday: { open: '12:00', close: '23:00', closed: false }, friday: { open: '12:00', close: '23:00', closed: false }, saturday: { open: '12:00', close: '23:00', closed: false }, sunday: { open: '12:00', close: '23:00', closed: false } }, contact: { phone: '+212 524 381 609', email: 'info@nomadmarrakech.com', website: 'https://nomadmarrakech.com' }, reservations: { required: true, online: true, phone: true }, worldCupFeatures: { matchScreening: false, fanMenu: true, groupBookings: true, multilingualMenu: true }, dietaryOptions: { vegetarian: true, vegan: true, glutenFree: true, halal: true }, atmosphere: ['Modern', 'Casual'], featured: true, isOpen: true }
];

async function seedFullDatabase() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('Connected to MongoDB');

    // Clear existing data
    await Hotel.deleteMany({});
    await Rental.deleteMany({});
    await Restaurant.deleteMany({});
    console.log('Cleared existing data');

    // Insert new data
    const hotels = await Hotel.insertMany(hotelsData);
    console.log(`Inserted ${hotels.length} hotels`);

    const rentals = await Rental.insertMany(rentalsData);
    console.log(`Inserted ${rentals.length} rentals`);

    const restaurants = await Restaurant.insertMany(restaurantsData);
    console.log(`Inserted ${restaurants.length} restaurants`);

    console.log('Full database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedFullDatabase();
